server:
  port: 8041
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heishandian/config-server-registry/    
          search-paths: default, system, bar*                            
          username:                                           
          password:                                             
          repos:
            simple: https://github.com/heishandian/simple/config-repo
            local2:
              search-paths: config-repo
              pattern: gcs*
              uri: file:D:\Temp\spring-cloud-config2
        health:
          repositories:
            a-fo1o:
              label: config-lab1el-v2.0
              name: microser1vice-foo
              profiles: dev